version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - bornday_data:/data/db 

  backend: 
    build: ./server
    container_name: backend_api
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    env_file:
      - ./server/.env 
    volumes:
      - ./server:/app
      - /app/node_modules
  
  frontend: 
    build: ./client
    container_name: frontend_app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:app
      - /app/node_modules
  
volumes:
  bornday_data: {}