version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - 27017:27017
    env_file:
      - ./server/.env
    volumes:
      - bornday_data:/data/db 

  backend: 
    build: ./server
    container_name: backend_api
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - ./server/.env 
    volumes:
      - ./server:/app
      - /app/node_modules
  
  frontend: 
    build: ./client
    container_name: frontend_app
    ports:
      - 5173:5173
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
  
volumes:
  bornday_data: {}