version: '3.8'

services:
  backend: 
    build: ./server
    container_name: backend_api
    ports:
      - 4000:4000
    env_file:
      - ./server/.env 
    volumes:
      - ./server:/app
      - /app/node_modules
    command: ["npm", "start"]
  
  frontend: 
    build: ./client
    container_name: frontend_app
    ports:
      - 5173:5173
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    