name: Schedule Birthday Notifications

on:
  schedule:
    - cron: "0 8 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  trigger-notifications:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}

    steps:
      - name: Call Notification API
        run: |
          curl -X POST "$BACKEND_URL/notifications/sendNotifications"
